### ISSUE TITLE
Pico 2 🥳 

### ISSUE THREAD

**Issue by Gadgetoid** [pinout-xyz/pico2.pinout.xyz#1]
# TODO

* [x] Replace .svg for front/back (in progress)
* [ ] Add new UART functions
* [x] Update the extra pin functions in the table at the bottom, I don't know how correct these are now... (No change, I don't think!)
* [ ] Make sure references to RP2040 are expunged
* [ ] Address issues at https://github.com/pinout-xyz/pico.pinout.xyz/issues/19  (test pad will get fixed by the new images)

**Comment by cfpwastaken** [comment]
Now that we have 3 different pico versions (excluding H-versions) with a 4th one coming maybe the link to the other version (the one that shows "Pico W pinout" on pico.pinout.xyz and "Pico pinout" on picow.pinout.xyz) should be reworked to a select menu?
